version: '3'

services:
  nose_index:
    container_name: nose_index_wakuta
    image: yusukew/nose_index
    tty: true
  mysql:
    container_name: mysql_nose
    build: ./backend/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --max_allowed_packet=32505856 
