version: '2'
services:
  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    container_name: mysql_nose
    build: ./mysql
    volumes_from:
      - db_data
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --max_allowed_packet=32505856 
  cassandra:
    container_name: cassandra_nose
    build: ./cassandra
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
  tpccmysql:
    container_name: tpcc_mysql_nose
    build: ./tpcc-mysql/tpcc-mysql
    tty: true
